apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik.example.com
  namespace: traefik
spec:
  dnsNames:
    - traefik.example.com
  secretName: traefik.example.com
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer