apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin.example.com
spec:
  dnsNames:
    - pgadmin.example.com
  secretName: pgadmin.example.com
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer