apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx.example.com
spec:
  dnsNames:
    - nginx.example.com
  secretName: nginx.example.com
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer