apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd.example.com
  namespace: argocd
spec:
  dnsNames:
    - argocd.example.com
  secretName: argocd.example.com
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer