apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins.example.com
  namespace: jenkins
spec:
  dnsNames:
    - jenkins.example.com
  secretName: jenkins.example.com
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer